- .babelrc
- .eslintignore
- .eslintrc
- .gitignore
- .travis.yml
- appveyor.yml
- index.js
- package.json
- src/app/app.html
- src/app/app.js
- src/app/index.js
- src/app/store.js
- test/sample.test.js
- test/setup.js
- webpack.config.development.js
Integrated project structure with source, test, build process and lint checker.
> feat/project_structure: update project structure

- .travis.yml
- appveyor.yml
Travis and Appveyor configuration cleaned up.
> fix/ci_clean_up: update CI configuration

- index.js
- locales/en.json
- package.json
- src/ffi/client_manager.js
MAID-1743 Expose Login API
MAID-1745 Expose create new account API
> MAID-1743 and MAID-1745

- locales/en.json
- src/ffi/client_manager.js
- test/client.test.js
- test/sample.test.js
- test/setup.js
MAID-1746 Test cases for create new account API
MAID-1744 Test cases for Login API
> MAID-1746 and MAID-1744

- locales/en.json
- src/ffi/client_manager.js
- src/ffi/constants.json
- test/client.test.js
- test/utils.js
MAID-1747 Expose get authorised application API
MAID-1748 Test cases for get authorised application API
> MAID-1747 and MAID-1748

- locales/en.json
- src/ffi/client_manager.js
- test/client.test.js
MAID-1749 Expose revoke application API
MAID-1750 Test cases for revoke application API
> MAID-1749 and MAID-1750

- src/ffi/client_manager.js
- test/client.test.js
MAID-1751 Expose logout API
MAID-1752 Test cases for logout API
> MAID-1751 and MAID-1752

- index.js
- locales/en.json
- package.json
- src/ffi/client_manager.js
- src/protocols/safe_auth.js
- src/protocols/safe_auth_rpc.js
- test/client.test.js
Integrated `safeauth` protocol.
> MAID-1753 Register safe-auth scheme from plugin

- package.json
- src/app/index.js
- src/app/sass/base.scss
- src/app/sass/colors.scss
- src/app/sass/main.scss
- src/app/sass/mixins.scss
- src/app/sass/variables.scss
- webpack.config.development.js
> MAID-1754 SafeAuth home page - setup SASS

- locales/en.json
- package.json
- src/app/components/alert.js
- src/app/components/login.js
- src/app/containers/login_container.js
- src/app/img/show_password.svg
- src/app/img/show_password_active.svg
- src/app/img/show_password_hover.svg
- src/app/reducers/app.js
- src/app/reducers/auth.js
- src/app/reducers/index.js
- src/app/router.js
- src/app/sass/base.scss
- src/app/sass/button.scss
- src/app/sass/common.scss
- src/app/sass/form.scss
- src/app/sass/heading.scss
- src/app/sass/main.scss
- src/app/utils.js
Updated html conversion of login page.
> MAID-1756 SafeAuth home page - Login page html conversion

- src/app/components/app_list.js
- src/app/components/app_list_item.js
- src/app/containers/app.js
- src/app/containers/app_list_container.js
- src/app/img/safedrive_icon.svg
- src/app/router.js
- src/app/sass/app_list.scss
- src/app/sass/header.scss
- src/app/sass/main.scss
MAID-1759 SafeAuth home page - Application list html conversion
MAID-1760 SafeAuth home page - Application detail view html conversion
> MAID-1759 and MAID-1760 

- locales/en.json
- src/app/actions/auth.js
- src/app/components/create_account.js
- src/app/components/create_account_password.js
- src/app/components/create_account_secret.js
- src/app/components/create_account_welcome.js
- src/app/components/login.js
- src/app/containers/login.js
- src/app/reducers/auth.js
> MAID-1763 SafeAuth home - Integrate login with API

- .babelrc
- index.js
- locales/en.json
- package.json
- src/api/client.js
- src/api/ffiLoader.js
- src/api/index.js
- src/app/actions/app.js
- src/app/actions/auth.js
- src/app/components/app.js
- src/app/components/app_list.js
- src/app/components/app_list_item.js
- src/app/components/create_account.js
- src/app/components/login.js
- src/app/constants.json
- src/app/containers/app.js
- src/app/containers/app_list.js
- src/app/containers/login.js
- src/app/index.js
- src/app/reducers/app.js
- src/app/reducers/auth.js
- src/app/reducers/network_state.js
- src/app/sass/app_list.scss
- src/app/sass/header.scss
- src/app/utils.js
- src/ffi/client_manager.js
- src/protocols/safe_auth.js
- webpack.config.api.js
- webpack.config.development.js
- webpack.config.protocol.js
MAID-1764 SafeAuth home - Integrate get authorised applications API
MAID-1765 SafeAuth home - Integrate revoke application API
MAID-1766 SafeAuth home - Integrate logout
> MAID-1764, MAID-1765 and MAID-1766

- .eslintrc
- .gitmodules
- .travis.yml
- appveyor.yml
- locales/en.json
- package.json
- src/api/client.js
- src/app/actions/app.js
- src/app/components/app.js
- src/app/components/app_list_item.js
- src/app/index.js
- src/app/reducers/app.js
- src/app/sass/app_list.scss
- src/config.js
- src/ffi/client_manager.js
- src/ffi/model/types.js
- src/ffi/model/typesParsers.js
- src/protocols/safe_auth_rpc.js
- test/client.test.js
- webpack.config.protocol.js
Implemented native modules and fixed CI.
> MAID-1871 Setup - Git sub modules for authenticator beaker plugin and update CI scripts

- .gitmodules
Submodule updated to use `maidsafe/safe_client_libs`
> chore/submodule_update: updated submodule

- README.md
> chore/readme: update README

- .gitignore
- .gitmodules
- README.md
- grep_error_codes.js
- index.js
- package.json
- src/api/client.js
- src/constants.json
- src/ffi/client_manager.js
- src/ffi/error_code_lookup.json
- src/ffi/ffi_loader.js
- src/ffi/model/types.js
- src/ffi/model/typesConstructor.js
- src/ffi/model/typesParsers.js
- src/ffi/sys_uri_loader.js
- src/protocols/safe_auth.js
- test/client.test.js
- webpack.config.api.js
- webpack.config.protocol.js
Update to build on Window's platform.
> Windows build

- src/protocols/safe_auth_rpc.js
Updated auth response URI to URL safe one.
> fix/auth_response_uri: update auth response uri

- .travis.yml
- appveyor.yml
- package.json
- src/ffi/client_manager.js
- test/client.spec.js
Updated APIs and test cases to support latest safe_client_libs
> MAID-1983 Update to latest safe_client_libs

- src/protocols/safe_auth.js
Updated safe_browser path on scheme registration
> fix/safe_browser_exec_path: update safe_browser path

- src/protocols/safe_auth_rpc.js
Resolved open URI issue on windows platform
> fix/open_url: resolve open url issue on windows

- .travis.yml
- README.md
- appveyor.yml
- build_libs.js
- package.json
Updated README.MD and build script.
> feat/README.MD: update readme and build script

- src/ffi/client_manager.js
- src/protocols/safe_auth_rpc.js
- test/client.spec.js
Updated IPC to handle web client.
> MAID-2007 fix/IPC_handling: update IPC to handle web client

- .travis.yml
- README.md
- appveyor.yml
- build_libs.js
- package.json
Updated README.md.
Updated build script for native library.
Travis timeout issue fixed.
> Update README.md and build script for native libraries

- appveyor.yml
Updated rustup installer script on appveyor
> Update appveyor.yml for dev branch

- src/ffi/client_manager.js
- src/protocols/safe_auth_rpc.js
- test/client.spec.js
Merged dev branch into master.
> Merge dev into master

- .travis.yml
- README.md
- appveyor.yml
- build_libs.js
- package.json
Updated README.MD and build script.
> Updated README.md and build script

- src/protocols/safe_auth.js
> fix/Setting the system-uri path to electron app's path

- .travis.yml
- appveyor.yml
- build_libs.js
- package.json
- test/client.spec.js
Updated build script to handle errors and print log instantly.
Updated submodules.
> Update build script

- build_libs.js
Resolved build issue on windows platform.
> Build issue on windows platform

- src/ffi/client_manager.js
- test/client.spec.js
Updated create account to invite based approach.
Updated test cases.
> Invite based account creation

- locales/en.json
- src/api/client.js
- src/app/actions/auth.js
- src/app/components/create_account.js
- src/app/components/create_account_password.js
- src/app/components/invite_code.js
- src/app/containers/create_account.js
- src/app/index.js
- src/app/reducers/auth.js
- src/app/sass/base.scss
- src/app/sass/form.scss
- src/constants.json
- src/ffi/client_manager.js
- test/client.spec.js
- test/helper.js
Updated with Invite code UI and test cases
> Update with invite code UI

- src/app/components/invite_code.js
- src/app/sass/button.scss
Temporarily disabled invite claim button.
> Disabled invite claim button

- .eslintrc
- .travis.yml
- appveyor.yml
- build_libs.js
- src/app/components/app_list_item.js
- src/ffi/client_manager.js
- src/ffi/refs/types.js
- src/ffi/refs/typesParser.js
Updated build script.
Updated to latest FfiResult of safe_client_libs.
Updated travis and appveyor scripts to use rust 1.17.0
> Fix build script and update to latest safe_client_libs

- package.json
- src/common.js
- src/ffi/client_manager.js
- src/protocols/safe_auth_rpc.js
- test/client.spec.js
- webpack.config.api.js
> Resolve reauthorise issue

- src/common.js
- src/ffi/client_manager.js
- src/protocols/safe_auth_rpc.js
Resolved re-authorise issue with web apps.
> Resolved re-authorise issue

- package.json
- src/ffi/client_manager.js
Updated comparison of JSON object with Lodash method.
> Update json object comparison 

- src/app/components/app_list.js
- src/app/containers/app.js
- src/app/containers/app_list.js
Updated with revoke app loading UI
> Revoke UI fix

- package.json
- src/ffi/client_manager.js
- webpack.config.api.js
Updated revoke function not to open response safe-url.
> Updated revoke function

- index.js
- src/api/client.js
- src/ffi/client_manager.js
- src/ffi/error_code_lookup.json
- test/client.spec.js
Implemented unregistered client req and response handle
> Implemented unregistered client

- src/ffi/client_manager.js
Resolve login and create_acc api async issue
> Auth APIs async issue

- .gitmodules
- src/app/components/auth_loader.js
- src/app/sass/form.scss
- src/ffi/client_manager.js
Updated API to support latest safe_client_libs
> Updated Auth API

- src/app/actions/app.js
- src/app/components/app_list.js
- src/app/containers/app_list.js
- src/app/reducers/app.js
- src/constants.json
Updated with error handling while revoke and fetch app list
> Error handling

- src/ffi/client_manager.js
Resolve decrypt request issue on windows to remove safe-auth protocol on windows platform.
> Resolve decrypt request issue on windows platform

- src/app/components/app_details.js
- src/app/containers/app_details.js
- src/app/reducers/app.js
Resolve fetch apps issue after revoked
> Resolved fetch apps issue

- src/app/components/create_account.js
- src/app/components/login.js
- src/app/sass/buttons.scss
- src/app/sass/card.scss
- src/app/sass/variables.scss
Resolve create account / login UI bugs and improved UX.
> Resolved minor UI bugs

- src/app/components/create_account.js
- src/ffi/ipc.js
Implemented feature to skip auth request
> Auth request skip

- package.json
Updated binary to pre34 release
> pre43 release

- src/app/components/create_account.js
Updated claim invite on creating account page
> Update claim invite

- .travis.yml
- appveyor.yml
- cleared unused globals
- removed x86 platform from appveyor
> fix/CI: resolve travis and appveyor

- src/app/sass/header.scss
- src/ffi/ipc.js
Resolved clickable link of reconnect.
Updated IPC response handling
> MAID-2163 Resolve clickable issue of reconnect link

- src/app/components/app_list.js
- src/app/sass/app.scss
- src/app/sass/card.scss
- src/app/sass/header.scss
- src/app/sass/loader.scss
Resolved following issues
Error popup doesn't close by clicking OK.
Search icon on expanding push the app list down.
Apps position keep changing on refresh. Sort apps by their names.
Reduce header size
The loading component overlay must have rounded edges
> MAID-2160 resolve UI related issues

- src/app/components/account_info.js
- src/app/sass/base.scss
- src/app/sass/card.scss
Fixed following issues
Change cursor of connected state to default
Change account status tooltip text to 'The number of store and modify operations completed on this account’
Change cursor of auth footer to default no disabled
> MAID-2182 resolve ui related issues

- package.json
Updated to pull pre45 dependencies
> Update to pull pre45

- src/app/components/account_info.js
- src/app/components/create_account.js
Show Infinite when account status available is huge number.
Handling on click of invitation form
> Minor ui changes

- src/app/components/app_list.js
Resolve popup showing success icon on error and handling error message on UI improved.
> Popup UI issue

- src/app/components/account_info.js
Resolved account info infinite issue
> Account info issue fix

- locales/en.json
- src/api/client.js
- src/app/actions/auth.js
- src/app/components/login.js
- src/app/containers/login.js
- src/app/index.js
- src/app/reducers/auth.js
- src/app/sass/base.scss
- src/ffi/authenticator.js
- src/ffi/lib.js
- src/ffi/safe_lib.js
- src/ffi/sys_uri.js
When libraries not loaded show pop-up on the initial screen of the authenticator and also disabled authorizing the user.
> MAID-2213 Update to handle library loading

- package.json
- src/constants.js
- src/ffi/authenticator.js
- src/ffi/ipc.js
- src/ffi/refs/constructors.js
- src/ffi/refs/parsers.js
- src/ffi/refs/types.js
Updated with MData IPC API for encode and decode
> MAID-2220 Update MDATA IPC API

- src/common.js
- src/ffi/authenticator.js
Updated lock option to handle both Auth request and container request.
> MAID-2252 Resolve lock option functionality issue

- .gitmodules
- package.json
- src/ffi/refs/constructors.js
- src/ffi/refs/parsers.js
- src/ffi/refs/types.js
- src/ffi/sys_uri.js
- test/client.spec.js
Updated permissionSet struct to adapt latest update on safe_client_libs.
Updated System URI API
Removed gitmodules
> MAID-2258 and MAID-2251

- src/app/utils.js
> MAID-2263 Resolve error handling

- src/app/components/app_details.js
- src/app/utils.js
- src/ffi/authenticator.js
- src/ffi/refs/parsers.js
- src/ffi/refs/types.js
Implemented to get app access MDATA on decode.
Fixed UI permission set handling
Rename App own container
> MAID-2261 Update app access api

- src/app/components/account_info.js
- src/app/components/app_details.js
- src/app/sass/app.scss
Resolved listing all permission on UI.
Permission list capitalizes.
Update account info colour calculation.
> MAID-2289 Permission list issue on UI

- src/app/components/app_list.js
Resolved to focus search input after expanding.
> MAID-2294 Fix search input focus issue

- src/common.js
- src/ffi/authenticator.js
On decoding auth request just check for app already exists in the list and don’t mind of what permission is requested.
> MAID-2301 Resolve re-authorise issue

- src/ffi/ipc.js
Implemented separate queue for unregistered clients.
> MAID-2300 implement unregistered queue

- src/ffi/ipc.js
Updated to standard request format
> Standard request format

- src/app/components/create_account.js
- test/client.spec.js
Reverts maidsafe/beaker-plugin-safe-authenticator#138
> Revert "MAID-2328: allows enter key to be used continue through form screens"

- CHANGELOG.MD
- package.json
**Change log**
- MutableData Authroisation support
- UserMetadata struct updated
- UI/UX improvements
- uses safe_authenticator v0.4.0
- uses system_uri v0.2.0
> version change to 0.3.0

- CHANGELOG.MD
- package.json
- uses safe_authenticator version e9080ac
> version change to 0.3.1
